export default [
    {
        "updated_at": "2020-05-03 15:31:59",
        "id": 187,
        "has_send_num": 0,
        "start_at": "2020-03-30 00:00",
        "end_at": "2020-05-15 23:59",
        "deleted_at": null,
        "buy_status": 1,
        "coupons": [
            {
                "detail": {
                    "coupon_use_time": [
                        {
                            "use_time_start": "00:00:00",
                            "use_time_end": "23:59:59"
                        }
                    ],
                    "updated_at": "1585539323",
                    "use_good_category": "限部分商品",
                    "category": 4,
                    "expire_days": 30,
                    "expire": "领券当日开始30天内有效",
                    "min_num": 1,
                    "number": 0,
                    "m_and_n_coupon_of_n": 1,
                    "property": 3,
                    "total": 99999999,
                    "property_text": "领取券",
                    "max_num": 0,
                    "coupon_amount": "买A赠B券",
                    "coupon_title": " ",
                    "discountGoods": [],
                    "scene_type_desc": " ",
                    "expire_ymd": "领券当日开始30天内有效",
                    "couponUseTime": [
                        {
                            "use_time_start": "00:00:00",
                            "use_time_end": "23:59:59"
                        }
                    ],
                    "template_id": "",
                    "created_at": "1585539323",
                    "scene_type": 3,
                    "desc": "        ",
                    "finance_payment": "4.5",
                    "title": "第2件半价券(mini卡)",
                    "second_max_num": 0,
                    "total_amount": 5,
                    "min_amount_use": 0,
                    "used": 0,
                    "goods_range_num": 1,
                    "explain_text": "       ",
                    "number_of_user": 0,
                    "id": "451347890055233536",
                    "use_per_person_per_day": 0,
                    "goods": [],
                    "min_num_use": 0,
                    "expire_type": 1,
                    "goods_range_type": 1,
                    "start_at": 0,
                    "image": "  ",
                    "end_at": 0,
                    "coupon_label": " ",
                    "multi_range_type": 2,
                    "shop_ids": "7559,5809",
                    "show_page": 1,
                    "is_koubei": "",
                    "use_category": " ",
                    "out_biz_no": "",
                    "only_coupon": 1,
                    "status": 1,
                    "coupon_type": 1,
                    "amount": "买A赠B券",
                    "is_use_time_range": 0,
                    "store_id": "23107",
                    "coupon_no": "",
                    "type": 1,
                    "discount_goods": [],
                    "is_receive": 1
                },
        "image": " ",
        "status": 2,
        "third_party_name": "",
        "third_party_id": 0,
        "send_num": 0,
        "created_at": "2020-03-30 23:17:24",
        "third_desc": "",
        "amount": "198.00",
        "content": "【     。",
        "limit_num": 0,
        "num": 100000,
        "store_id": 23107,
        "title": "霸气欢聚卡",
        "sale_num": 523,
        "third_status": 0
    }],
	}

]
